# Generated by Django 5.0 on 2023-12-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('universityID', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('stage', models.IntegerField()),
            ],
        ),
    ]
