# Generated by Django 5.0 on 2024-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_grade_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grades',
            field=models.CharField(max_length=255),
        ),
    ]
