# Generated by Django 5.0 on 2024-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_grade_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subjects',
            field=models.CharField(max_length=255),
        ),
    ]
